[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "talking_head"
version = "0.0.1"
requires-python = ">=3.10,<4.0"

[tool.setuptools]
packages = ["talking_head"]
