BatchSize: &BatchSize 4 
NumGPU: &NumGPU 1
NumNodes: &NumNodes 1
CkptPath: &CkptPath /mnt/data/yifanzhang/talking-head/model/sdxl_vae.safetensors
model:
  base_learning_rate: 5e-5
  target: talking_head.models.vae.models.autoencoder.AutoencodingEngine
  params:
    input_key: pixel_values
    ckpt_path: *CkptPath 
    disc_start_iter: 0

    encoder_config:
      target: talking_head.models.vae.modules.diffusionmodules.model.Encoder
      params:
        attn_type: vanilla-xformers
        double_z: true
        z_channels: 4
        resolution: 1024
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0

    decoder_config:
      target: talking_head.models.vae.modules.diffusionmodules.model.Decoder
      params:
        attn_type: vanilla-xformers
        double_z: true
        z_channels: 4
        resolution: 1024
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0

    regularizer_config:
      target: talking_head.models.vae.modules.autoencoding.regularizers.DiagonalGaussianRegularizer

    loss_config:
      target: talking_head.models.vae.modules.autoencoding.losses.GeneralLPIPSWithDiscriminator
      params:
        perceptual_weight: 0.25
        disc_start: 0
        disc_weight: 0.5
        learn_logvar: True

        regularization_weights:
          kl_loss: 1.0

data:
  target: talking_head.datasets.vae_dataset.VideoDataLoader
  params:
    batch_size: *BatchSize
    num_workers: 8
    prefetch_factor: 4
    shuffle: true
    train_config:
      target: talking_head.datasets.vae_dataset.VideoDataset
      params:
        data_dir: /mnt/data/public/dataset/talking_head/video_datasets/HDTF
        metadata_paths:
          - /mnt/data/public/dataset/talking_head/embeddings/HDTF/metadata.jsonl
        is_image: true
    validation_config:
      target: talking_head.datasets.vae_dataset.VideoDataset
      params:
        data_dir: /mnt/data/public/dataset/talking_head/video_datasets/HDTF
        metadata_paths:
          - /mnt/data/public/dataset/talking_head/embeddings/HDTF/metadata.jsonl  # TODO: Change this to the validation metadata
        is_image: true

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: True

  modelcheckpoint:
    params:
      every_n_train_steps: 5000

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 50000

    image_logger:
      target: talking_head.models.vae.util.ImageLogger
      params:
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    precision: 'bf16-mixed'
    devices: *NumGPU
    num_nodes: *NumNodes 
    #num_sanity_val_steps: 0
    # limit_val_batches: 50
    benchmark: True
    # accumulate_grad_batches: 1
    limit_val_batches: 0
    max_epochs: 1000
 